stages:
  - documentation

variables:
  DOCKER_DRIVER: overlay2

documenter_ci:
  stage: documentation
  image: terostech/colibri:latest
  script:
    - cd dev/ble_cdr
    - teroshdl-hdl-documenter -i ble_cdr.yml -o html --dep --fsm -s all -c all -p all --outpath built_doc
    - cd ../../
    - apt-get update && apt-get install -y rsync
    - mkdir -p public
    - ls -lah dev/ble_cdr/built_doc
    - rsync -av --delete dev/ble_cdr/built_doc/ public/
  artifacts:
    paths:
      - dev/ble_cdr/built_doc
      - public
    expire_in: 1 hour
  only:
    - dev

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
