stages:
  - documentation

variables:
  DOCKER_DRIVER: overlay2

documenter_ci:
  stage: documentation
  image: terostech/colibri:latest
  script:
    - apt-get update && apt-get install -y rsync
    - cd dev/ble_cdr
    - teroshdl-hdl-documenter -i ble_cdr.yml -o html --dep --fsm -s all -c all -p all --outpath built_doc
  artifacts:
    paths:
      - dev/ble_cdr/built_doc
  only:
    - dev

pages:
  stage: documentation
  script:
    - mkdir -p public
    - rsync -av --delete dev/ble_cdr/built_doc/ public/
  artifacts:
    paths:
      - public
  only:
    - dev